### PR TITLE
Include explicit returns to simplify conditional logic

### PR DESCRIPTION
**Pull request by Ironholds**
What it says on the tin; if we use return() we don't have to do the if-x-then-y-else-if-z-then...dance, because if one condition is met, the function terminates.

### CODE REVIEW

**Comment by cboettig** [comment]
Good point, this does simplify the logic.  I generally don't like `return()` statements, but then generally I should avoid functions with very conditional / variable return behavior anyway (I pretty much agree with http://adv-r.had.co.nz/Functions.html#return-values).  


More to the point, if I may ask, what brings you to look at this function anyway?  I'm not sure I ever really developed the sequential updating method properly.  My post-doc mentor (Steve, Matlab user) swears that for reasonably large data-sets it is hands down the fastest thing to do.  My R implementation of it here was pretty slow and I never used it.  Overall, this package isn't really hardened for general-purpose use; though there are about a dozen GP packages on CRAN now.  At least 2 of them are really good (though either didn't exist or I didn't know about at the time): FastGP and BigGP.  

FastGP is an RCpp implementation of the basic algorithms, has reasonable performance and its interface is quite easy to use. The authors have a decent paper on the arXiv about it, which is a good place to start: http://arxiv.org/pdf/1507.06055.pdf  In particular, includes a nice introduction to the package and comparisons to some of the other packages.  Notably, it does a nice job of exposing some of it's lower-level functions, which makes it suitable if you want to do a fully Bayesian inference; something that is impossible or basically impossible to do well and flexibly using other packages (including ones that you would think would, like tgp, which also has stability issues).  

If performance is limiting (e.g. larger data sets), BigGP is pretty much the only game in town (see http://www.jstatsoft.org/article/view/v063i10 for details).  It predates FastGP, though the authors of FastGP fail to compare (or even cite it), and is really geared towards HPC platforms (i.e. MPI, though you'll see benefits even on shared-memory parallelization).  As you might expect from such a package, the interface is a good deal more low-level, and you may need some care about dependencies to get it to compile properly.  But it kicks butt once it's going.  

Recently I've been playing with implementations of GPs in the general-purpose hierarchical modeling framework, nimble: http://r-nimble.org/.  It's still in alpha / active development but I highly recommend it if you're interested in this area.  

Anyway, thanks for the pull request!

**Comment by Ironholds** [comment]
I was idly browsing GitHub source code in some downtime.

**Comment by cboettig** [comment]
hehe, if you have cycles to burn I can point you to code that could more badly benefit from your expertise ;-)

**Comment by Ironholds** [comment]
Happy to take a look, although not guaranteeing anything!

**Comment by cboettig** [comment]
ha! You wouldn't have any experience wrapping C programs into R packages by any chance? (not proper libraries with clearly defined APIs, but just a bunch of C++ that compiles into a CLI tool).

Banging my head on this one: https://github.com/cboettig/rappl

**Comment by Ironholds** [comment]
Ooh, fun. I do! What problems are you running into? Happy to take a look if you e.g. throw the desired outcome/undesired error into an issue on the repo.

**Pull request merged**
